# export_datacenters.R
# Exports datacenter atlas to map/data/datacenters.js for the D3 map layer.
# Run once after datacenter_merge.R + echo_phase4.R:
#   source("export_datacenters.R")
#
# Requires: openxlsx, jsonlite

library(openxlsx)
library(jsonlite)

FINAL_PATH <- "datacenter_merged_final.xlsx"
OUT_JS     <- "map/data/datacenters.js"

wb  <- loadWorkbook(FINAL_PATH)
df  <- readWorkbook(wb, sheet = "Datacenters")
cat(sprintf("Loaded %d rows from %s\n", nrow(df), FINAL_PATH))

df$Latitude  <- suppressWarnings(as.numeric(df$Latitude))
df$Longitude <- suppressWarnings(as.numeric(df$Longitude))
df$mw        <- suppressWarnings(round(as.numeric(df$est_power_kw) / 1000, 1))

out <- df[!is.na(df$Latitude) & !is.na(df$Longitude), ]

clean_str <- function(x) {
  x <- as.character(x)
  x[is.na(x)] <- ""
  gsub('"', "'", x, fixed = TRUE)
}

out_json <- data.frame(
  n  = clean_str(out$Name),
  co = clean_str(out$Company),
  ci = clean_str(out$City),
  st = clean_str(out$State),
  la = round(out$Latitude,  5),
  lo = round(out$Longitude, 5),
  mw = out$mw,
  sc = clean_str(out$source_confidence),
  stringsAsFactors = FALSE
)

json_body <- toJSON(out_json, na = "null", digits = 5)
writeLines(
  paste0("/* Auto-generated by export_datacenters.R — do not edit */\nvar datacenterData = ", json_body, ";"),
  OUT_JS
)

cat(sprintf("Exported %d facilities to %s\n", nrow(out_json), OUT_JS))
cat(sprintf("  File size: %.1f KB\n", file.size(OUT_JS) / 1024))
