# export_county_mw.R
# 1. Aggregates datacenter MW estimates to county level → map/data/county_mw.js
# 2. Re-exports enriched facility list with county FIPS + full fields → map/data/datacenters.js
#
# Run after datacenter_merge.R + echo_phase4.R:
#   source("export_county_mw.R")
#
# Requires: openxlsx, dplyr, maps, jsonlite

library(openxlsx)
library(dplyr)
library(maps)
library(jsonlite)

FINAL_PATH  <- "datacenter_merged_final.xlsx"
COUNTY_JS   <- "map/data/county_mw.js"
FAC_JS      <- "map/data/datacenters.js"

wb  <- loadWorkbook(FINAL_PATH)
df  <- readWorkbook(wb, sheet = "Datacenters")
cat(sprintf("Loaded %d rows\n", nrow(df)))

df$lat <- suppressWarnings(as.numeric(df$Latitude))
df$lon <- suppressWarnings(as.numeric(df$Longitude))
df$mw  <- suppressWarnings(as.numeric(df$est_power_kw)) / 1000

df <- df[!is.na(df$lat) & !is.na(df$lon) & !is.na(df$mw), ]
cat(sprintf("  %d with valid coords and MW\n", nrow(df)))

# ── Reverse geocode lat/lon → county FIPS ─────────────────────────────────────
cat("Reverse geocoding to counties...\n")
df$county_poly <- maps::map.where("county", df$lon, df$lat)
cat(sprintf("  %d / %d matched to a county\n", sum(!is.na(df$county_poly)), nrow(df)))

data(county.fips, package = "maps")
cf <- county.fips
cf$poly_clean <- sub(":.*$", "", as.character(cf$polyname))
df$poly_clean <- sub(":.*$", "", as.character(df$county_poly))

df_merged <- merge(df, cf[, c("fips", "poly_clean")],
                   by = "poly_clean", all.x = TRUE)

# Drop merge-induced duplicates (multi-part county polygons)
df_merged <- df_merged[!duplicated(paste(df_merged$Name, df_merged$lat, df_merged$lon)), ]
cat(sprintf("  %d / %d matched to FIPS\n", sum(!is.na(df_merged$fips)), nrow(df_merged)))

# ── County aggregates ─────────────────────────────────────────────────────────
county_agg <- df_merged |>
  filter(!is.na(fips)) |>
  group_by(fips) |>
  summarise(mw = round(sum(mw, na.rm = TRUE), 1), n = n(), .groups = "drop") |>
  mutate(fips = sprintf("%05d", as.integer(fips))) |>
  arrange(desc(mw))

cat(sprintf("\nTop 10 counties by estimated MW:\n"))
print(head(county_agg, 10))
cat(sprintf("\n%d counties total | %.1f GW aggregate\n\n",
            nrow(county_agg), sum(county_agg$mw) / 1000))

writeLines(
  paste0("/* Auto-generated by export_county_mw.R */\nvar countyMwData = ",
         toJSON(county_agg, dataframe = "rows"), ";"),
  COUNTY_JS
)
cat(sprintf("Exported county aggregates to %s\n", COUNTY_JS))

# ── Enriched facility list (replaces datacenters.js) ─────────────────────────
clean_str <- function(x) {
  x <- as.character(x); x[is.na(x)] <- ""
  gsub('"', "'", x, fixed = TRUE)
}

safe_num <- function(x, digits = 2) suppressWarnings(round(as.numeric(x), digits))
safe_int <- function(x)             suppressWarnings(as.integer(x))

fac_out <- data.frame(
  n        = clean_str(df_merged$Name),
  co       = clean_str(df_merged$Company),
  ci       = clean_str(df_merged$City),
  st       = clean_str(df_merged$State),
  adr      = clean_str(df_merged$Address),
  la       = round(df_merged$lat, 5),
  lo       = round(df_merged$lon, 5),
  mw       = df_merged$mw,
  sc       = clean_str(df_merged$source_confidence),
  fips     = ifelse(is.na(df_merged$fips), "",
                    sprintf("%05d", as.integer(df_merged$fips))),
  util     = clean_str(df_merged$primary_utility),
  grid     = clean_str(df_merged$eia_grid_region),
  rto      = clean_str(df_merged$eia_rto),
  cost     = safe_num(df_merged$est_annual_cost_musd, 2),
  sqft     = safe_int(df_merged$es_floor_space_sqft),
  echo_air = clean_str(df_merged$echo_air_flag),
  campus_n = safe_int(df_merged$campus_building_count),
  stringsAsFactors = FALSE
)

writeLines(
  paste0("/* Auto-generated by export_county_mw.R */\nvar datacenterData = ",
         toJSON(fac_out, na = "null", digits = 5), ";"),
  FAC_JS
)
cat(sprintf("Exported %d facilities to %s\n", nrow(fac_out), FAC_JS))
cat(sprintf("  File sizes: county=%.0fKB  facilities=%.0fKB\n",
            file.size(COUNTY_JS) / 1024, file.size(FAC_JS) / 1024))
