"""
Export approved review-queue bills to map/data/bills_pipeline.js.

The map loads this file alongside states.js and merges the entries
into each state's panel at render time.
"""

import json
from datetime import datetime, timezone
from pathlib import Path

from .db import get_conn

MAP_DIR       = Path(__file__).parent.parent / "map" / "data"
PIPELINE_FILE = MAP_DIR / "bills_pipeline.js"


def load_pipeline() -> dict:
    """Read current bills_pipeline.js → {STATE: {bill_number: entry}}"""
    if not PIPELINE_FILE.exists():
        return {}
    # Skip comment lines, find the JSON object starting with {
    lines = PIPELINE_FILE.read_text(encoding="utf-8").splitlines()
    json_lines = []
    in_json = False
    for line in lines:
        if not in_json:
            stripped = line.strip()
            if stripped.startswith("//"):
                continue
            # Strip JS variable declaration to isolate the JSON object
            for prefix in ("const PIPELINE_BILLS =", "window.PIPELINE_BILLS ="):
                if stripped.startswith(prefix):
                    stripped = stripped[len(prefix):].strip()
                    line = stripped
                    break
            if line.strip().startswith("{"):
                in_json = True
        if in_json:
            json_lines.append(line)

    text = "\n".join(json_lines).strip().rstrip(";")
    try:
        return json.loads(text)
    except Exception:
        return {}


def write_pipeline(data: dict):
    MAP_DIR.mkdir(parents=True, exist_ok=True)
    ts  = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    out = (
        f"// Auto-generated by legiscan/export.py — do not edit manually\n"
        f"// Last updated: {ts}\n"
        f"const PIPELINE_BILLS = "
        + json.dumps(data, indent=2, ensure_ascii=False)
        + ";\n"
    )
    PIPELINE_FILE.write_text(out, encoding="utf-8")


def export_approved() -> dict:
    """
    Write all approved queue entries to bills_pipeline.js.
    Returns {"new": int, "updated": int, "total": int}.
    """
    pipeline = load_pipeline()
    new_count = updated_count = 0

    with get_conn() as conn:
        rows = conn.execute(
            "SELECT * FROM queue WHERE review_status = 'approved' ORDER BY state, bill_number"
        ).fetchall()

    for row in rows:
        state   = row["state"]
        bill_no = row["bill_number"]
        tags    = [t for t in (row["tags"] or "").split(",") if t.strip()]
        entry   = {
            "text":       (row["summary"] or row["title"] or "").strip(),
            "url":        row["url"] or "",
            "tags":       tags,
            "confidence": round(float(row["confidence"] or 0), 2),
            "source":     "legiscan",
        }

        if state not in pipeline:
            pipeline[state] = {}

        if bill_no not in pipeline[state]:
            new_count += 1
        elif pipeline[state][bill_no] != entry:
            updated_count += 1

        pipeline[state][bill_no] = entry

    write_pipeline(pipeline)
    total = sum(len(v) for v in pipeline.values())
    return {"new": new_count, "updated": updated_count, "total": total}


def get_export_stats() -> dict:
    """Return counts for display: approved in queue vs already in pipeline."""
    pipeline = load_pipeline()
    pipeline_total = sum(len(v) for v in pipeline.values())

    with get_conn() as conn:
        approved = conn.execute(
            "SELECT COUNT(*) FROM queue WHERE review_status = 'approved'"
        ).fetchone()[0]

    return {"approved_in_queue": approved, "in_pipeline": pipeline_total}


if __name__ == "__main__":
    result = export_approved()
    print(f"Export complete: {result['new']} new, {result['updated']} updated, {result['total']} total in pipeline")
